const products = [
  { "id": 1, "name": "4th Street Red 5L", "category": "Wine", "price": 4148, "image": "images/wine/4th-street-red-5l.jpg" },
  { "id": 2, "name": "4th Street Red 750ml", "category": "Wine", "price": 888, "image": "images/wine/4th-street-red-750ml.png" },
  { "id": 3, "name": "Bon Voyage Dry Red", "category": "Wine", "price": 880, "image": "images/wine/bon-voyage-dry-red.jpeg" },
  { "id": 4, "name": "Bon Voyage Sweet Red", "category": "Wine", "price": 880, "image": "images/wine/bon-voyage-sweet-red.webp" },
  { "id": 5, "name": "Cellar Red 5L", "category": "Wine", "price": 4193, "image": "images/wine/cellar-red-5l.jpeg" },
  { "id": 6, "name": "Cellar Red 750ml", "category": "Wine", "price": 977, "image": "images/wine/cellar-red-750ml.jpg" },
  { "id": 7, "name": "Drostdy Red 5L", "category": "Wine", "price": 4440, "image": "images/wine/drostdy-red-5l.jpg" },
  { "id": 8, "name": "Drostdy Red 750ml", "category": "Wine", "price": 953, "image": "images/wine/drostdy-red-750ml.jpg" },
  { "id": 9, "name": "Nederburg Cabernet Sauvignon", "category": "Wine", "price": 1985, "image": "images/wine/nederburg-cabernet-sauvignon.webp" },
  { "id": 10, "name": "Nederburg Merlot", "category": "Wine", "price": 1901, "image": "images/wine/nederburg-merlot.jpg" },
  { "id": 11, "name": "Nederburg Pinotage", "category": "Wine", "price": 1901, "image": "images/wine/nederburg-pinotage.jpg" },
  { "id": 12, "name": "Nederburg Shiraz", "category": "Wine", "price": 1901, "image": "images/wine/nederburg-shiraz.jpg" },
  { "id": 13, "name": "Robertson Red 750ml", "category": "Wine", "price": 1026, "image": "images/wine/robertson-red-750ml.jpg" },
  { "id": 14, "name": "Rosso Nobile Cioccolatta", "category": "Wine", "price": 1539, "image": "images/wine/rosso-nobile-cioccolatta.webp" },
  { "id": 15, "name": "4th Street White 5L", "category": "Wine", "price": 3980, "image": "images/wine/4th-street-white-5l.jpg" },
  { "id": 16, "name": "4th Street White 750ml", "category": "Wine", "price": 888, "image": "images/wine/4th-street-white-750ml.jpg" },
  { "id": 17, "name": "Cellar White 5L", "category": "Wine", "price": 4273, "image": "images/wine/cellar-white-5l.jpeg" },
  { "id": 18, "name": "Cellar White 750ml", "category": "Wine", "price": 946, "image": "images/wine/cellar-white-750ml.jpeg" },
  { "id": 19, "name": "Nederburg Sauvignon Blanc", "category": "Wine", "price": 1608, "image": "images/wine/nederburg-sauvignon-blanc.jpeg" },
  { "id": 20, "name": "Nederburg Chardonnay", "category": "Wine", "price": 1901, "image": "images/wine/nederburg-chardonnay.jpg" },
  { "id": 21, "name": "Robertson White 750ml", "category": "Wine", "price": 1026, "image": "images/wine/robertson-white-750ml.jpg" },
  { "id": 22, "name": "Bianco Nobile", "category": "Wine", "price": 1425, "image": "images/wine/bianco-nobile.jpg" },
  { "id": 23, "name": "Alta Wine Kwal", "category": "Wine", "price": 1400, "image": "images/wine/alta-wine-kwal.png" },

  { "id": 24, "name": "Jack Daniels 1L", "category": "Whisky", "price": 3339, "image": "images/whisky/jack-daniels-1l.jpg" },
  { "id": 25, "name": "Jack Daniels 750ml", "category": "Whisky", "price": 2756, "image": "images/whisky/jack-daniels-750ml.png" },
  { "id": 26, "name": "Jack Daniels 350ml", "category": "Whisky", "price": 1836, "image": "images/whisky/jack-daniels-350ml.jpg" },
  { "id": 27, "name": "Jack Daniels Honey 1L", "category": "Whisky", "price": 3816, "image": "images/whisky/jack-daniels-honey-1l.jpg" },
  { "id": 28, "name": "Jack Daniels Honey 750ml", "category": "Whisky", "price": 3392, "image": "images/whisky/jack-daniels-honey-750ml.jpg" },
  { "id": 29, "name": "Jack Daniels Legacy", "category": "Whisky", "price": 3210, "image": "images/whisky/jack-daniels-legacy.webp" },
  { "id": 30, "name": "Gentleman Jack 1L", "category": "Whisky", "price": 6254, "image": "images/whisky/gentleman-jack-1l.jpg" },
  { "id": 31, "name": "Gentleman Jack 700ml", "category": "Whisky", "price": 4740, "image": "images/whisky/gentleman-jack-700ml.jpg" },
  { "id": 32, "name": "John Barr Black 1L", "category": "Whisky", "price": 1765, "image": "images/whisky/john-barr-black-1l.webp" },
  { "id": 33, "name": "John Barr Black 750ml", "category": "Whisky", "price": 1431, "image": "images/whisky/john-barr-black-750ml.jpg" },
  { "id": 34, "name": "John Barr Red 1L", "category": "Whisky", "price": 1658, "image": "images/whisky/john-barr-red-1l.jpeg" },
  { "id": 35, "name": "Johnnie Walker Black Label 1L", "category": "Whisky", "price": 4035, "image": "images/whisky/jw-black-label-1l.webp" },
  { "id": 36, "name": "Johnnie Walker Black Label 750ml", "category": "Whisky", "price": 3335, "image": "images/whisky/jw-black-label-750ml.jpg" },
  { "id": 37, "name": "Glenfiddich 12Y 1L", "category": "Whisky", "price": 7689, "image": "images/whisky/glenfiddich-12y-1l.avif" },
  { "id": 38, "name": "Glenfiddich 12Y 700ml", "category": "Whisky", "price": 6149, "image": "images/whisky/glenfiddich-12y-700ml.png" },
  { "id": 39, "name": "Glenfiddich 15Y", "category": "Whisky", "price": 8549, "image": "images/whisky/glenfiddich-15y.jpg" },
  { "id": 40, "name": "Glenfiddich 18Y", "category": "Whisky", "price": 13144, "image": "images/whisky/glenfiddich-18y.jpeg" },
  { "id": 41, "name": "Grant's 1L", "category": "Whisky", "price": 2226, "image": "images/whisky/grants-1l.jpg" },
  { "id": 42, "name": "Famous Grouse 1L", "category": "Whisky", "price": 2398, "image": "images/whisky/famous-grouse-1l.jpg" },
  { "id": 43, "name": "Famous Grouse 750ml", "category": "Whisky", "price": 1893, "image": "images/whisky/famous-grouse-750ml.jpg" },
  { "id": 44, "name": "Monkey Shoulder 1L", "category": "Whisky", "price": 5940, "image": "images/whisky/monkey-shoulder-1l.jpeg" },
  { "id": 45, "name": "Monkey Shoulder 750ml", "category": "Whisky", "price": 4752, "image": "images/whisky/monkey-shoulder-750ml.jpeg" },
  { "id": 46, "name": "VAT 69 1L", "category": "Whisky", "price": 1908, "image": "images/whisky/vat-69-1l.jpg" },
  { "id": 47, "name": "VAT 69 750ml", "category": "Whisky", "price": 1449, "image": "images/whisky/vat-69-750ml.png" },

  { "id": 48, "name": "Absolut Vodka 1L", "category": "Vodka", "price": 2401, "image": "images/vodka/absolut-vodka-1l.jpg" },
  { "id": 49, "name": "Smirnoff 1L", "category": "Vodka", "price": 1651, "image": "images/vodka/smirnoff-1l.jpg" },
  { "id": 50, "name": "Konyagi 250ml", "category": "Vodka", "price": 240, "image": "images/vodka/konyagi-250ml.jpg" },
  { "id": 51, "name": "Konyagi 500ml", "category": "Vodka", "price": 470, "image": "images/vodka/konyagi-500ml.webp" },
  { "id": 52, "name": "Konyagi 750ml", "category": "Vodka", "price": 674, "image": "images/vodka/konyagi-750ml.jpeg" },
  { "id": 53, "name": "All Seasons 1L", "category": "Vodka", "price": 1325, "image": "images/vodka/all-seasons-1l.jpeg" },
  { "id": 54, "name": "All Seasons 750ml", "category": "Vodka", "price": 1164, "image": "images/vodka/all-seasons-750ml.jpeg" },
  { "id": 55, "name": "All Seasons 350ml", "category": "Vodka", "price": 582, "image": "images/vodka/all-seasons-350ml.jpeg" },
  { "id": 56, "name": "All Seasons 250ml", "category": "Vodka", "price": 399, "image": "images/vodka/all-seasons-250ml.jpeg" },

  { "id": 57, "name": "Gordon's Gin 1L", "category": "Gin", "price": 2462, "image": "images/gin/gordons-gin-1l.jpg" },
  { "id": 58, "name": "Hendrick's Gin 1L", "category": "Gin", "price": 6469, "image": "images/gin/hendricks-gin-1l.jpg" },
  { "id": 59, "name": "Hendrick's Gin 750ml", "category": "Gin", "price": 4876, "image": "images/gin/hendricks-gin-750ml.jpg" },

  { "id": 60, "name": "Hennessy VS 1L", "category": "Brandy & Cognac", "price": 7208, "image": "images/brandy/hennessy-vs-1l.jpg" },
  { "id": 61, "name": "Hennessy VSOP 1L", "category": "Brandy & Cognac", "price": 10812, "image": "images/brandy/hennessy-vsop-1l.jpg" },
  { "id": 62, "name": "Hennessy VSOP 750ml", "category": "Brandy & Cognac", "price": 8321, "image": "images/brandy/hennessy-vsop-750ml.jpg" },
  { "id": 63, "name": "Martell VS 700ml", "category": "Brandy & Cognac", "price": 4854, "image": "images/brandy/martell-vs-700ml.jpg" },
  { "id": 64, "name": "Martell VSOP 700ml", "category": "Brandy & Cognac", "price": 7212, "image": "images/brandy/martell-vsop-700ml.jpg" },
  { "id": 65, "name": "Remy Martin VSOP 750ml", "category": "Brandy & Cognac", "price": 8155, "image": "images/brandy/remy-martin-vsop-750ml.jpg" },
  { "id": 66, "name": "Remy Martin VSOP 1L", "category": "Brandy & Cognac", "price": 9835, "image": "images/brandy/remy-martin-vsop-1l.jpg" },

  { "id": 67, "name": "Jose Cuervo Gold 1L", "category": "Tequila", "price": 2862, "image": "images/tequila/jose-cuervo-gold-1l.jpg" },
  { "id": 68, "name": "Jose Cuervo Gold 750ml", "category": "Tequila", "price": 2544, "image": "images/tequila/jose-cuervo-gold-750ml.jpg" },
  { "id": 69, "name": "Jose Cuervo Silver 1L", "category": "Tequila", "price": 2862, "image": "images/tequila/jose-cuervo-silver-1l.jpg" },
  { "id": 70, "name": "Jose Cuervo Silver 750ml", "category": "Tequila", "price": 2544, "image": "images/tequila/jose-cuervo-silver-750ml.jpg" },
  { "id": 71, "name": "Tequila Camino Gold", "category": "Tequila", "price": 2332, "image": "images/tequila/tequila-camino-gold.jpg" },
  { "id": 72, "name": "Tequila Camino Clear", "category": "Tequila", "price": 2354, "image": "images/tequila/tequila-camino-clear.jpg" },

  { "id": 73, "name": "Bacardi Clear 1L", "category": "Rum", "price": 2307, "image": "images/rum/bacardi-clear-1l.jpg" },

  { "id": 74, "name": "Amarula 1L", "category": "Liqueur", "price": 2226, "image": "images/liqueur/amarula-1l.jpg" },
  { "id": 75, "name": "Amarula 750ml", "category": "Liqueur", "price": 2067, "image": "images/liqueur/amarula-750ml.jpeg" },
  { "id": 76, "name": "Jagermeister 1L", "category": "Liqueur", "price": 3498, "image": "images/liqueur/jagermeister-1l.jpg" },
  { "id": 77, "name": "Jagermeister 700ml", "category": "Liqueur", "price": 2248, "image": "images/liqueur/jagermeister-700ml.jpg" },
  { "id": 78, "name": "Kahlua 750ml", "category": "Liqueur", "price": 2648, "image": "images/liqueur/kahlua-750ml.jpg" },
  { "id": 79, "name": "Sheridan's 1L", "category": "Liqueur", "price": 4786, "image": "images/liqueur/sheridans-1l.jpg" },
  { "id": 80, "name": "Martini Bianco", "category": "Liqueur", "price": 1867, "image": "images/liqueur/martini-bianco.jpg" },
  { "id": 81, "name": "Martini Rosso", "category": "Liqueur", "price": 1796, "image": "images/liqueur/martini-rosso.jpg" },
  { "id": 82, "name": "Southern Comfort 1L", "category": "Liqueur", "price": 2860, "image": "images/liqueur/southern-comfort-1l.jpg" },
  { "id": 83, "name": "Southern Comfort 750ml", "category": "Liqueur", "price": 1818, "image": "images/liqueur/southern-comfort-750ml.jpg" },

  { "id": 84, "name": "Angostura Bitters 200ml", "category": "Bitters", "price": 2491, "image": "images/bitters/angostura-bitters-200ml.jpg" },

  { "id": 85, "name": "Monster Energy Drink", "category": "Non-Alcoholic", "price": 200, "image": "images/non-alcoholic/monster-energy-drink.jpg" },
  { "id": 86, "name": "OJ 16%", "category": "Non-Alcoholic", "price": 342, "image": "images/non-alcoholic/oj-16-percent.jpg" }
];
